// <auto-generated />
using System;
using EcoReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoReport.Migrations
{
    [DbContext(typeof(EcoReportContext))]
    [Migration("20260321212915_FixPonto")]
    partial class FixPonto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoReport.Models.Ponto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Arquivo")
                        .HasColumnType("text");

                    b.Property<string>("ArquivoDes")
                        .HasColumnType("text");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Ponto");
                });

            modelBuilder.Entity("EcoReport.Models.PontoTipoDeArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("PontoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoDeAreaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PontoId");

                    b.HasIndex("TipoDeAreaId");

                    b.ToTable("PontoTipoDeArea");
                });

            modelBuilder.Entity("EcoReport.Models.TipoDeArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoDeArea");
                });

            modelBuilder.Entity("EcoReport.Models.PontoTipoDeArea", b =>
                {
                    b.HasOne("EcoReport.Models.Ponto", "Ponto")
                        .WithMany()
                        .HasForeignKey("PontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoReport.Models.TipoDeArea", "TipoDeArea")
                        .WithMany()
                        .HasForeignKey("TipoDeAreaId");

                    b.Navigation("Ponto");

                    b.Navigation("TipoDeArea");
                });
#pragma warning restore 612, 618
        }
    }
}
